window.quotes = [
  { content: "BUEHHHHHHH", author: "Kamiyama Shiki" },
  { content: "Shizuku is fundamentally boobs.", author: "Tsumugi Wenders" },
  { content: "You. Are. Lolicon.", author: "Katou Umi" },
  { content: "The people of this island have a blind faith in woks…", author: "Takahara Hairi" },
  { content: "I suppose the world isn't ready for something as revolutionary as communal boobs.", author: "Mizuori Shizuku" },
  { content: "Dragon of the Darkness Flaaaaaaame!", author: "Katou Umi" },
  { content: "Your boobs are not to be given away willy-nilly for others to touch.", author: "Mizuori Shizuku" },
  { content: "I'm not digging this hole idea.", author: "Takahara Hairi" },
  { content: "Is this what they call an American joke?", author: "Katou Umi" },
  { content: "It's okay. If you don't get caught, is the same as if you didn't do it at all.", author: "Takahara Hairi" },
  { content: "I've gotta breathe. It comes with living.", author: "Takahara Hairi" },
  { content: "Rei-Dan!", author: "Naruse Shiroha" },
  { content: "When you look at boobs, the boobs look back.", author: "Mizuori Shizuku" },
  { content: "I can see... the light at the end of nudity's tunnel!", author: "Mitani Ryouichi" },
  { content: "Leave it to a Japanese person to not say 'no' outright.", author: "Takahara Hairi" },
  { content: "She went ahead and not only named, but cried over my non-existent dog.", author: "Takahara Hairi" },
  { content: "What a waste of oxygen you are...", author: "Katou Umi" },
  { content: "I think I would've rather taken the bullet over following some random half-naked guy to some deserted corner of an island!", author: "Takahara Hairi" },
  { content: "I use all my strength to clench my butt cheeks together and run.", author: "Takahara Hairi" },
  { content: "A front door's only a moving wall to keep out bugs and wind, y'know.", author: "Kamiyama Shiki" },
  { content: "And there's even that weird rule on this island to shoot any nudists on sight!", author: "Mitani Ryouichi" },
  { content: "All I am is 90% fatty tissue and 10% mammary glands.", author: "Mizuori Shizuku" },
  { content: "Argumentative men will be single all their life, you know.", author: "Kamiyama Shiki" },
  { content: "Even if that's the case...everyone's primary worry is the size of their boobies, right?", author: "Mizuori Shizuku" },
  { content: "I cried until her boobies were soaking wet.", author: "Tsumugi Wenders" },
  { content: "I don't know how to cope with a world where I can't take off my shirt freely.", author: "Mitani Ryouichi" },
  { content: "It seems like their boobs give them a connection.", author: "Takahara Hairi" },
  { content: "Nudism was my singular focus already at that age.", author: "Mitani Ryouichi" },
  { content: "The kids' booby chant continues to swell.", author: "Takahara Hairi" },
  { content: "There comes a time when you meet someone somewhere and you come to think it was all a process meant to prepare you to be of help to that person.", author: "Takahara Hairi" },
  { content: "There is nothing wrong with reading romance manga.", author: "Katou Umi" },
  { content: "Wh-What's wrong with me?! I forgot to give boob-centric advice!", author: "Mizuori Shizuku" },
  { content: "Your eyes... They tell me you're fascinated by boobies.", author: "Mizuori Shizuku" },
  { content: "You smell like a cheater.", author: "Katou Umi" }
];
